name: CI - Pull Request

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
      - name: Install library
        run: |
          pip install -r requirements.txt
      - name: Run Pytest
        run: |
          pytes t

      - name: Basic check
        run: echo "PR checks passed"

  docker:
    needs: check
    uses: ./.github/workflows/docker-build.yml
    with:
      push_image: false
